---
title: "GSE131013"
output:
  pdf_document: default
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(include = FALSE)
knitr::opts_knit$set(root.dir = "/mnt/local-disk/data/guoxiaolong/Renv")
```

```{r packages}
source("~/code/Dmathy/Damthy.R")
```

```{r}
library(data.table)
library(minfi)
series <- t(fread("~/data/infinium/colon/GSE131013_series_matrix.txt",header = T))
colnames(series) <- series[1,]
series <- series[-1,]
series <- as.data.frame(series)
colnames(series) <- c("tissue","stage","sex","age","location")
idx <- which(series$location == "")
series$age[idx]<-series$sex[idx]
series$sex[idx]<-series$stage[idx]
series <- series[,-c(2,5)]
series$age <-  as.numeric(sapply(strsplit(series$age, " "), function(x) x[[2]]))
series$sex <- ifelse(grepl("Male",series$sex),1,0)
series$tissue <-  sapply(strsplit(series$tissue, " "), function(x) x[[2]])
```

```{r}
GPL <- fread("~/data/infinium/GPL13534/GPL13534-11288.txt", sep = "\t", header = T)
rgset <- read.metharray.exp("~/data/infinium/colon/idat")
rawDat <- f.rawD(GPL = GPL,rgset = rgset,series = series)
raw.o <- f.raw.o(rawDat)
# coverage
coverage(raw.o)
raw.o <- imp(raw.o)
series$disease <- ifelse(series$tissue == "Normal",0,1)
raw.o@raw.s <- series
save(raw.o,file = "GSE131013_raw.Rd")
```

```{r}
qc.o <- f.qc.o(raw.o)
qc.o@beta_dtr[[1]]

he.o <- f.he.o(qc.o)
save(qc.o,file = "GSE131013_qc.Rd")
save(he.o,file = "GSE131013_he.Rd")
```
