---
title: "GSE107038"
output:
  pdf_document: default
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(include = FALSE)
knitr::opts_knit$set(root.dir = "/mnt/local-disk/data/guoxiaolong/Renv")
```

```{r packages}
source("~/code/Dmathy/Damthy.R")
library(minfi)
```

```{r}
rgset <- read.metharray.exp("~/data/infinium/liver_sample/40_normal_liver_samples/idat")
series <- t(read.table("~/data/infinium/liver_sample/40_normal_liver_samples/series.txt",header = T))[-1,]
library(data.table)
GPL <- fread("~/data/infinium/GPL_files/GPL13534/GPL13534-11288.txt", sep = "\t", header = T)
rawDat <- f.rawD(GPL = GPL,rgset = rgset,series = series)
raw.o <- f.raw.o(rawDat)
```

annotation

```{r}

age <- as.numeric(sapply(strsplit(series[,12], " "), function(x) x[[2]]))
sex <- sapply(strsplit(series[,13], " "), function(x) x[[2]])
sex <- as.numeric(ifelse(sex=="Male",1,0))
sentrixID<-as.factor(sapply(strsplit(colnames(raw.o@raw.m),"_"),function(x) x[[2]]))
sentrixPos <- as.factor(sapply(strsplit(colnames(raw.o@raw.m),"_"),function(x) x[[3]]))
s <- data.frame(age,sex,sentrixID,sentrixPos)
raw.o@raw.s <- s
raw.o <- imp(raw.o)
raw.o@beta_dtr <- list(beta_dtp(raw.o))
```

qc.o

```{r}
qc.o <- f.qc.o(raw.o)
qc.o@beta_dtr[[1]]
qc.o@ctf.o <- CTF(qc.o,mrefLiver.m)
# GSM2859966_9247377073_R05C01 outliers
idx <- which(colnames(qc.o@m) == "GSM2859966_9247377073_R05C01")
qc.o@m <- qc.o@m[,-idx]
qc.o@s <- qc.o@s[-idx,]
rownames(qc.o@s) <- sapply(strsplit(colnames(qc.o@m),"_"),function(x) x[[1]])
qc.o@ctf.o <- CTF(qc.o,mrefLiver.m)
qc.o@svd.o <- lm_svd(qc.o)
p_h(qc.o,pic = c(27,5))
```

CellDMC

```{r}
library(EpiDISH)
covs <- model.matrix(~qc.o@s$sentrixID)
celldmc.o <- CellDMC(qc.o@m, qc.o@s$age ,qc.o@ctf.o[[1]], 
                     cov.mod = covs, 
                     adjPMethod = "fdr",
                     adjPThresh = 0.05, 
                     sort = FALSE,
                     mc.cores = 100)
dmcts<- celldmc.o$dmct
sum(dmcts[,2] != 0) 
sum(dmcts[,4] != 0) 
sum(dmcts[,3] != 0) 
sum(dmcts[,5] != 0) 
coefs <- celldmc.o$coe
all_t <- as.data.frame(lapply(coefs, function(x) x$t))
rownames(all_t) <- rownames(coefs$Chol)
#FDR threshold
fdr_threshold_Chol<- min(abs(coefs$Chol$t[sapply(coefs$Chol$adjP, function(x) {x<=0.1})]))# 0.05, 0.1
fdr_threshold_Hep <- min(abs(coefs$Hep$t[sapply(coefs$Hep$adjP, function(x) {x<=0.1})]))
pdf("DMCTs.pdf", width=6,height=6)
smoothScatter(all_t[, "Chol"], all_t[, "Hep"], xlab = "t -stat. (CellDMC:Chol)", 
              ylab = "t -stat. (CellDMC:Hep)", 
              xlim = c(-9,9), ylim = c(-9,9), cex = 1.5, 
              main = "CT specific age-DMCs predicted by CellDMC")
abline(v = 0, lty = 2, col = "black")
abline(h = 0, lty = 2, col = "black")
abline(v = fdr_threshold_Chol, lty = 2, col = "blue")
abline(v = -fdr_threshold_Chol, lty = 2, col = "blue")
abline(h = fdr_threshold_Hep, lty = 2, col = "blue")
abline(h = -fdr_threshold_Hep, lty = 2, col = "blue")
dev.off()
```

combine

```{r}
bat <- rep("add",times = nrow(he_61258.o@s))
hes <- data.frame(he_61258.o@s[,1:2],sentrixID = bat)
sn <- rbind(qc.o@s[,1:3],hes)
mn <- merge(qc.o@m,he_61258.o@m,by=0)
rownames(mn)<- mn$Row.names
qc.on <- new("qc.o")
qc.on@m <- as.matrix(mn[,-1])
qc.on@s <- sn
qc.on@ctf.o <- CTF(qc.on,mrefLiver.m,type = "450k")
qc.on@svd.o <- lm_svd(qc.on)
p_h(qc.on,pic = c(27,5))


```

CellDMC

```{r}
library(EpiDISH)
covs <- model.matrix(~qc.on@s$sentrixID)
celldmc.o2 <- CellDMC(qc.on@m, qc.on@s$age ,qc.on@ctf.o[[1]], 
                     cov.mod = covs, 
                     adjPMethod = "fdr",
                     adjPThresh = 0.05,
                     sort = FALSE,
                     mc.cores = 40)
dmcts<- celldmc.o$dmct
sum(dmcts[,2] != 0) 
sum(dmcts[,4] != 0) 
sum(dmcts[,3] != 0) 
sum(dmcts[,5] != 0) 
coefs <- celldmc.o2$coe
all_t <- as.data.frame(lapply(coefs, function(x) x$t))
rownames(all_t) <- rownames(coefs$Chol)
#FDR threshold
fdr_threshold_Chol<- min(abs(coefs$Chol$t[sapply(coefs$Chol$adjP, function(x) {x<=0.1})]))
fdr_threshold_Hep <- min(abs(coefs$Hep$t[sapply(coefs$Hep$adjP, function(x) {x<=0.1})]))
pdf("DMCTs.pdf", width=6,height=6)
smoothScatter(all_t[, "Chol"], all_t[, "Hep"], xlab = "t -stat. (CellDMC:Chol)", 
              ylab = "t -stat. (CellDMC:Hep)", 
              xlim = c(-9,9), ylim = c(-9,9), cex = 1.5, 
              main = "CT specific age-DMCs predicted by CellDMC")
abline(v = 0, lty = 2, col = "black")
abline(h = 0, lty = 2, col = "black")
abline(v = fdr_threshold_Chol, lty = 2, col = "blue")
abline(v = -fdr_threshold_Chol, lty = 2, col = "blue")
abline(h = fdr_threshold_Hep, lty = 2, col = "blue")
abline(h = -fdr_threshold_Hep, lty = 2, col = "blue")
dev.off()
```
