---
title: "GSE76938"
output:
  pdf_document: default
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(include = FALSE)
knitr::opts_knit$set(root.dir = "/mnt/local-disk/data/guoxiaolong/Renv")
```

```{r packages}
source("~/code/Dmathy/Damthy.R")
```

```{r data}
m <- fread("~/data/infinium/prostate/GSE76938_matrix_processed.txt")
load("~/data/infinium/GPL21145/annoEPICv1B4.Rd")
GPL <- as.data.frame(annoEPICv1B4.m)
series <- t(fread("~/data/infinium/prostate/series.txt",header = T))
colnames(series) <- series[1,]
series <- series[-1,]
colnames(series) <- c("disease","age","ETH")
series[,2] <-  as.numeric(sapply(strsplit(series[,2], " "), function(x) x[[2]]))
series <- as.data.frame(series)
names <- rownames(series)
series <- series[!is.na(series$age),]
series$disease <- ifelse(grepl("cancer",series$disease),1,0)
series$ETH <- ifelse(grepl("Caucasian",series$ETH),"Cau","AA")
rawDat <- f.rawD(GPL=GPL,m_pval=m, series = series)
raw.o <- f.raw.o(rawDat)
raw.o@raw.s <- series
colnames(raw.o@raw.m) <- names
idx <- match(rownames(raw.o@raw.s),colnames(raw.o@raw.m))
raw.o@raw.m <- raw.o@raw.m[,idx]
raw.o@raw.p <- raw.o@raw.p[,idx]

coverage(raw.o)
raw.o <- imp(raw.o)
```

```{r qc}
raw.o@beta_dtr <- beta_dtp(raw.o)
raw.o@beta_dtr[[1]]
qc.o <- f.qc.o(raw.o)
qc.o@beta_dtr[[1]]

qc.o@ctf.o <- CTF(qc.o,mrefProstate.m)
qc.o@s$age <- as.numeric(qc.o@s$age)
qc.o@s$ETH <- as.factor(qc.o@s$ETH)
qc.o@svd.o <- lm_svd(qc.o)
p_h(qc.o,pic = c(28,2))
save(qc.o,file = "GSE76938_qc.Rd")
hey.o <- f.he.o(qc.o)
hey.o@ctf.o <- CTF(hey.o,mrefProstate.m)
hey.o@svd.o <- lm_svd(hey.o)
p_h(hey.o,pic = c(28,2))

```
