---
title: "GSE79100"
output:
  pdf_document: default
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(include = FALSE)
knitr::opts_knit$set(root.dir = "/mnt/local-disk/data/guoxiaolong/Renv")
```

```{r packages}
source("~/code/Dmathy/Damthy.R")
```

```{r input}
library(data.table)
library(minfi)
series <- t(fread("~/data/infinium/kidney/GSE79100/series.txt",header = F))
colnames(series) <- series[1,]
series <- series[-1,]
rownames(series) <- series[,1]
series <- series[,-1]
colnames(series) <- c("sex","ETH","age")
series <- as.data.frame(series)
series[,3] <-  as.numeric(sapply(strsplit(series[,3], " "), function(x) x[[2]]))
sex <- sapply(strsplit(series[,1], " "), function(x) x[[2]])
series[,1] <- as.numeric(ifelse(sex=="Male",1,0))
series[,2] <- sapply(strsplit(series[,2], " "), function(x) x[[2]])
series[,2] <- as.factor(ifelse(series[,2]=="European","EA","AA"))

GPL <- fread("~/data/infinium/GPL_files/GPL13534/GPL13534-11288.txt", sep = "\t", header = T)
rgset <- read.metharray.exp("~/data/infinium/kidney/GSE79100/idat/")
```

```{r}
rawDat <- f.rawD(GPL = GPL,rgset = rgset)
raw.o <- f.raw.o(rawDat)
# coverage
coverage(raw.o)
raw.o <- imp(raw.o)
raw.o@raw.s <- series
raw.o@beta_dtr <- beta_dtp(raw.o)
raw.o@beta_dtr[[1]]
```

```{r}
qc.o <- f.qc.o(raw.o)
qc.o@beta_dtr[[1]]

```
